name: checkinpromobile
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.5+102

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  esc_pos_printer: ^3.1.6
  dropdown_formfield: ^0.1.3
  wifi: ^0.1.5
  ntp: ^1.0.7
  ping_discover_network: ^0.2.0+1
  shared_preferences: ^0.5.6+2
  permission_handler: ^3.2.2
  convex_bottom_bar: ^2.6.0
  flare_flutter: ^2.0.3
  provider: ^3.0.0+1
  share: ^0.6.5+4
  path_provider:
  auto_size_text: ^2.1.0
  flutter_image_compress: ^0.6.5+1
  flutter_exif_rotation: ^0.2.7
  native_device_orientation: ^0.3.0
  keyboard_visibility: ^0.5.2
  rounded_loading_button: ^1.0.8
  package_info: ^0.4.0+3
  device_info: ^0.4.2+1
  chopper: ^2.4.2
  launch_review: ^1.0.1
  carousel_slider: ^2.3.1
  wakelock: ^0.1.4+2
  firebase_messaging: ^6.0.15
  flutter_local_notifications: ^4.0.1+2
  get_it: ^4.0.0
  simple_animations: ^2.2.1
  connectivity: ^0.4.3+2
  http: ^0.12.0+4
  async: ^2.4.0
  pull_to_refresh: ^1.6.3
  shimmer: ^1.1.1
  url_launcher: ^5.5.0
  json_annotation:
  image: ^2.1.12
  location: ^3.2.4
  flutter_camera_ml_vision: ^2.3.0
  sleek_circular_slider: ^1.2.0+web
  uuid: ^2.2.2
  flutter_widget_from_html: ^0.4.1
  flutter_widget_from_html_core: ^0.4.1
  sqlite3_flutter_libs: ^0.4.0+1
  moor: ^3.4.0
  flutter_spinkit: ^4.1.2+1
  overlay_support: ^1.0.5
  flutter_rating_bar: ^3.2.0+1
  blurrycontainer: ^0.0.1
  image_gallery_saver: ^1.6.7
  fluttertoast: ^7.1.6
  image_picker: ^0.6.6+5
  photo_manager: ^0.6.0
  audioplayers: ^0.17.3
  custom_refresh_indicator: ^0.9.0
  vibration: ^1.7.3
  intl_phone_number_input: ^0.5.2+2
  expandable: ^4.1.4
  network_image_to_byte: ^0.0.1
  group_radio_button: ^1.0.1
  app_settings: ^4.0.4
  transparent_image: ^1.0.0
  timeago: ^2.0.30
  argon_buttons_flutter: ^1.0.6
  flutter_device_type: ^0.3.2
  flutter_secure_storage: ^3.3.5
  table_calendar: ^2.3.3
  numeric_keyboard: ^1.0.1
  data_connection_checker: ^0.3.4
  simple_gesture_detector: ^0.1.5
  cupertino_icons: ^0.1.3
  local_auth: ^0.6.3+4
  synchronized: ^2.2.0+2
  fluro: ^1.7.8
  flutter_svg: ^0.18.0
  date_time_picker: ^1.1.1
  dropdown_search:
    git:
      url: https://github.com/checkinpro/searchable_dropdown.git
      ref: master
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: master
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  flutter_datetime_picker:
    git:
      url: https://github.com/checkinpro/cip_datetime_picker.git
      ref: master
  cip_flutter_charts:
    git:
      url: https://github.com/checkinpro/cip_chart.git
      ref: master
  cached_network_image: ^2.5.0
  flutter_slidable: ^0.5.7
  escposprinter:
    git:
      url: https://github.com/marcusfelix/esc-pos-printer-flutter.git
      ref: master
  syncfusion_flutter_calendar:
    git:
      url: https://github.com/checkinpro/super-calendar.git
      ref: main
  # checkbox_grouped:
  #   git:
  #     url: https://github.com/checkinpro/checkbox_grouped.git
  #     ref: main

dev_dependencies:
  moor_generator: ^3.1.0
  flutter_test:
    sdk: flutter
  build_runner:
  chopper_generator:
  built_value_generator:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design:
    true
    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/tflite/
    - assets/flare/
    - assets/sounds/
    - survey.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

    - family: HelveticaLight
      fonts:
        - asset: assets/fonts/Helvetica-light.ttf

    - family: HelveticaTraLight
      fonts:
        - asset: assets/fonts/Helvetica-tralight.ttf
        
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
