# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the App center"
  lane :deploy_appcenter do
    gradle(task: "assemble",
    build_type: "Release",
    properties: {
      "versionCode" => 1,
      "versionName" => "1.4.0",
      "android.injected.signing.store.file" => "/Volumes/DATA/Github/cip_today_mobile/checkinpromobile/checkinpromobile/android/key-cip",
      "android.injected.signing.store.password" => "123456",
      "android.injected.signing.key.alias" => "key-cip",
      "android.injected.signing.key.password" => "654321",
    })
    appcenter_upload(
      api_token: '35dd1f634424b68df532368a70dd282e5b12bfaa',
      owner_name: 'leewonghao-hotmail.com',
      app_name: 'CheckInPro-Today-1'
    )
  end
end
